---
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a dynamic inventory
      add_host:
        hostname: "{{ item.hostname }}"
        ansible_host: 192.168.233.60
        groups: chkp
        vm_name: "{{ item.hostname }}"
      with_items:
      - { hostname: vnf01 }

- name: playbook name
  hosts: chkp
  connection: httpapi
  vars:
    ansible_api_key: ltUlJCWk4fAoIEPf5juPGA==
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_network_os: check_point.mgmt.checkpoint
  tasks:
    - name: task to have network
      check_point.mgmt.cp_mgmt_network:
        name: "network name"
        subnet: "4.1.76.0"
        mask_length: 24
        auto_publish_session: true
        state: present

      vars:
        ansible_checkpoint_domain: "SMC User"