---
## Run with extra vars for example: 
# ansible-playbook provisioning-lsm-gw.yml -e "dms_ip=192.168.233.11 mgmt_server_name=nordics-dms11 ansible_checkpoint_domain=nordics"
##Required vars
# dms_ip=[DMS / SMS IP]
# mgmt_server_name=[DMS / SMS objectname]
## Optional var
# ansible_checkpoint_domain=[domain name]
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a dynamic inventory
      add_host:
        hostname: "{{ item.hostname }}"
        ansible_host: "{{ dms_ip }}"
        groups: chkp
        vm_name: "{{ item.hostname }}"
      with_items:
      - { hostname: vnf01 }
#      - { hostname: vnf02 }
#      - { hostname: vnf03 }
#      - { hostname: vnf04 }
#      - { hostname: vnf05 }

- name:  Add and config CG edge
  hosts: chkp
  gather_facts: no
  roles:
  - role: ./roles/chkp-lsm-gw
    connection: httpapi
    state: present
