---
# handlers file for logging out of the Check Point APIs

 - name: Logout
   uri:
      url: "https://{{ api_server }}{{ api_base_url }}/logout"
      validate_certs: "{{ api_validate_cert }}"
      method: POST
      body_format: json
      body: '{}'
      headers : 
        X-chkp-sid : "{{ sid }}"
   listen: "API logout handler"
   when: api_base_url.find("ZeroTouch") == -1

 - name: Logout from Zero-Touch
   uri:
      url: "https://{{ api_server }}{{ api_base_url }}/logout"
      validate_certs: "{{ api_validate_cert }}"
      method: POST
      body_format: json
      body: ''
      headers : 
        X-chkp-sid : "{{ sid }}"
   listen: "API logout handler"
   when: api_base_url.find("ZeroTouch") != -1