---
- import_tasks: zt_get_account.yml
  tags: [ "unclaim-gaia-gateway" ]
- import_tasks: zt-add-gaia-template.yml
- import_tasks: zt-claim-gaia-gateway.yml
- import_tasks: zt-unclaim-gaia-gateway.yml
  tags: [ "never","unclaim-gaia-gateway" ]
- import_tasks: trigger-chkp-api-logout.yml
  tags: [ "unclaim-gaia-gateway" ]